export const inputs = [
  {
    semester: "1",
    pai: "pai-1",
    pkn: "pkn-1",
    bindo: "bindo-1",
    mtk: "mtk-1",
    ipa: "ipa-1",
    ips: "ips-1",
    bing: "bing-1",
  },
  {
    semester: "2",
    pai: "pai-2",
    pkn: "pkn-2",
    bindo: "bindo-2",
    mtk: "mtk-2",
    ipa: "ipa-2",
    ips: "ips-2",
    bing: "bing-2",
  },
  {
    semester: "3",
    pai: "pai-3",
    pkn: "pkn-3",
    bindo: "bindo-3",
    mtk: "mtk-3",
    ipa: "ipa-3",
    ips: "ips-3",
    bing: "bing-3",
  },
  {
    semester: "4",
    pai: "pai-4",
    pkn: "pkn-4",
    bindo: "bindo-4",
    mtk: "mtk-4",
    ipa: "ipa-4",
    ips: "ips-4",
    bing: "bing-4",
  },
  {
    semester: "5",
    pai: "pai-5",
    pkn: "pkn-5",
    bindo: "bindo-5",
    mtk: "mtk-5",
    ipa: "ipa-5",
    ips: "ips-5",
    bing: "bing-5",
  },
];
